name       : perl-class-singleton
version    : '1.6'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHAY/Class-Singleton-1.6.tar.gz : 27ba13f0d9512929166bbd8c9ef95d90d630fc80f0c9a1b7458891055e9282a4
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Implementation of a "Singleton" class
description: |
    Implementation of a "Singleton" class
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
