name       : perl-class-singleton
version    : '1.5'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/S/SH/SHAY/Class-Singleton-1.5.tar.gz : 38220d04f02e3a803193c2575a1644cce0b95ad4b95c19eb932b94e2647ef678
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Implementation of a "Singleton" class
description: |
    Implementation of a "Singleton" class
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
