name       : perl-class-singleton
version    : 1.03
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/A/AB/ABW/Class-Singleton-1.03.tar.gz : c644be2f45ac61c56348df7a45f129495a54835fc717d558f45f83caab3109b1
license    : Artistic-2.0
component  : programming.perl
summary    : Implementation of a "Singleton" class
description: |
    Implementation of a "Singleton" class
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
